# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_simplesrcsinkproxy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pb_simplecapability_pb2 as pb__simplecapability__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_simplesrcsinkproxy.proto',
  package='journey11.kpubsubai.simple',
  syntax='proto3',
  serialized_pb=_b('\n\x1bpb_simplesrcsinkproxy.proto\x12\x1ajourney11.kpubsubai.simple\x1a\x19pb_simplecapability.proto\"|\n\x14PBSimpleSrcSinkProxy\x12\r\n\x05_name\x18\x01 \x01(\t\x12\x0e\n\x06_topic\x18\x02 \x01(\t\x12\x45\n\r_capabilities\x18\x03 \x03(\x0b\x32..journey11.kpubsubai.simple.PBSimpleCapabilityb\x06proto3')
  ,
  dependencies=[pb__simplecapability__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBSIMPLESRCSINKPROXY = _descriptor.Descriptor(
  name='PBSimpleSrcSinkProxy',
  full_name='journey11.kpubsubai.simple.PBSimpleSrcSinkProxy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_name', full_name='journey11.kpubsubai.simple.PBSimpleSrcSinkProxy._name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='_topic', full_name='journey11.kpubsubai.simple.PBSimpleSrcSinkProxy._topic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='_capabilities', full_name='journey11.kpubsubai.simple.PBSimpleSrcSinkProxy._capabilities', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=210,
)

_PBSIMPLESRCSINKPROXY.fields_by_name['_capabilities'].message_type = pb__simplecapability__pb2._PBSIMPLECAPABILITY
DESCRIPTOR.message_types_by_name['PBSimpleSrcSinkProxy'] = _PBSIMPLESRCSINKPROXY

PBSimpleSrcSinkProxy = _reflection.GeneratedProtocolMessageType('PBSimpleSrcSinkProxy', (_message.Message,), dict(
  DESCRIPTOR = _PBSIMPLESRCSINKPROXY,
  __module__ = 'pb_simplesrcsinkproxy_pb2'
  # @@protoc_insertion_point(class_scope:journey11.kpubsubai.simple.PBSimpleSrcSinkProxy)
  ))
_sym_db.RegisterMessage(PBSimpleSrcSinkProxy)


# @@protoc_insertion_point(module_scope)
