# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_simplesrcsinkping.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pb_uniqueworkref_pb2 as pb__uniqueworkref__pb2
import pb_simplesrcsinkproxy_pb2 as pb__simplesrcsinkproxy__pb2
import pb_simplecapability_pb2 as pb__simplecapability__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_simplesrcsinkping.proto',
  package='journey11.kpubsubai.simple',
  syntax='proto3',
  serialized_pb=_b('\n\x1apb_simplesrcsinkping.proto\x12\x1ajourney11.kpubsubai.simple\x1a\x16pb_uniqueworkref.proto\x1a\x1bpb_simplesrcsinkproxy.proto\x1a\x19pb_simplecapability.proto\"\xef\x01\n\x13PBSimpleSrcSinkPing\x12\x37\n\t_work_ref\x18\x01 \x01(\x0b\x32$.journey11.kpubsubai.PBUniqueWorkRef\x12O\n\x15_sender_srcsink_proxy\x18\x02 \x01(\x0b\x32\x30.journey11.kpubsubai.simple.PBSimpleSrcSinkProxy\x12N\n\x16_required_capabilities\x18\x03 \x03(\x0b\x32..journey11.kpubsubai.simple.PBSimpleCapabilityb\x06proto3')
  ,
  dependencies=[pb__uniqueworkref__pb2.DESCRIPTOR,pb__simplesrcsinkproxy__pb2.DESCRIPTOR,pb__simplecapability__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBSIMPLESRCSINKPING = _descriptor.Descriptor(
  name='PBSimpleSrcSinkPing',
  full_name='journey11.kpubsubai.simple.PBSimpleSrcSinkPing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_work_ref', full_name='journey11.kpubsubai.simple.PBSimpleSrcSinkPing._work_ref', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='_sender_srcsink_proxy', full_name='journey11.kpubsubai.simple.PBSimpleSrcSinkPing._sender_srcsink_proxy', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='_required_capabilities', full_name='journey11.kpubsubai.simple.PBSimpleSrcSinkPing._required_capabilities', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=378,
)

_PBSIMPLESRCSINKPING.fields_by_name['_work_ref'].message_type = pb__uniqueworkref__pb2._PBUNIQUEWORKREF
_PBSIMPLESRCSINKPING.fields_by_name['_sender_srcsink_proxy'].message_type = pb__simplesrcsinkproxy__pb2._PBSIMPLESRCSINKPROXY
_PBSIMPLESRCSINKPING.fields_by_name['_required_capabilities'].message_type = pb__simplecapability__pb2._PBSIMPLECAPABILITY
DESCRIPTOR.message_types_by_name['PBSimpleSrcSinkPing'] = _PBSIMPLESRCSINKPING

PBSimpleSrcSinkPing = _reflection.GeneratedProtocolMessageType('PBSimpleSrcSinkPing', (_message.Message,), dict(
  DESCRIPTOR = _PBSIMPLESRCSINKPING,
  __module__ = 'pb_simplesrcsinkping_pb2'
  # @@protoc_insertion_point(class_scope:journey11.kpubsubai.simple.PBSimpleSrcSinkPing)
  ))
_sym_db.RegisterMessage(PBSimpleSrcSinkPing)


# @@protoc_insertion_point(module_scope)
