# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_simplesrcsinkpingnotification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pb_uniqueworkref_pb2 as pb__uniqueworkref__pb2
import pb_simplesrcsinkproxy_pb2 as pb__simplesrcsinkproxy__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_simplesrcsinkpingnotification.proto',
  package='journey11.kpubsubai.simple',
  syntax='proto3',
  serialized_pb=_b('\n&pb_simplesrcsinkpingnotification.proto\x12\x1ajourney11.kpubsubai.simple\x1a\x16pb_uniqueworkref.proto\x1a\x1bpb_simplesrcsinkproxy.proto\"\xf7\x01\n\x1fPBSimpleSrcSinkPingNotification\x12\x37\n\t_work_ref\x18\x01 \x01(\x0b\x32$.journey11.kpubsubai.PBUniqueWorkRef\x12R\n\x18_responder_srcsink_proxy\x18\x02 \x01(\x0b\x32\x30.journey11.kpubsubai.simple.PBSimpleSrcSinkProxy\x12G\n\r_address_book\x18\x03 \x03(\x0b\x32\x30.journey11.kpubsubai.simple.PBSimpleSrcSinkProxyb\x06proto3')
  ,
  dependencies=[pb__uniqueworkref__pb2.DESCRIPTOR,pb__simplesrcsinkproxy__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBSIMPLESRCSINKPINGNOTIFICATION = _descriptor.Descriptor(
  name='PBSimpleSrcSinkPingNotification',
  full_name='journey11.kpubsubai.simple.PBSimpleSrcSinkPingNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_work_ref', full_name='journey11.kpubsubai.simple.PBSimpleSrcSinkPingNotification._work_ref', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='_responder_srcsink_proxy', full_name='journey11.kpubsubai.simple.PBSimpleSrcSinkPingNotification._responder_srcsink_proxy', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='_address_book', full_name='journey11.kpubsubai.simple.PBSimpleSrcSinkPingNotification._address_book', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=371,
)

_PBSIMPLESRCSINKPINGNOTIFICATION.fields_by_name['_work_ref'].message_type = pb__uniqueworkref__pb2._PBUNIQUEWORKREF
_PBSIMPLESRCSINKPINGNOTIFICATION.fields_by_name['_responder_srcsink_proxy'].message_type = pb__simplesrcsinkproxy__pb2._PBSIMPLESRCSINKPROXY
_PBSIMPLESRCSINKPINGNOTIFICATION.fields_by_name['_address_book'].message_type = pb__simplesrcsinkproxy__pb2._PBSIMPLESRCSINKPROXY
DESCRIPTOR.message_types_by_name['PBSimpleSrcSinkPingNotification'] = _PBSIMPLESRCSINKPINGNOTIFICATION

PBSimpleSrcSinkPingNotification = _reflection.GeneratedProtocolMessageType('PBSimpleSrcSinkPingNotification', (_message.Message,), dict(
  DESCRIPTOR = _PBSIMPLESRCSINKPINGNOTIFICATION,
  __module__ = 'pb_simplesrcsinkpingnotification_pb2'
  # @@protoc_insertion_point(class_scope:journey11.kpubsubai.simple.PBSimpleSrcSinkPingNotification)
  ))
_sym_db.RegisterMessage(PBSimpleSrcSinkPingNotification)


# @@protoc_insertion_point(module_scope)
