# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_uniqueworkref.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_uniqueworkref.proto',
  package='journey11.kpubsubai',
  syntax='proto3',
  serialized_pb=_b('\n\x16pb_uniqueworkref.proto\x12\x13journey11.kpubsubai\"\x1f\n\x0fPBUniqueWorkRef\x12\x0c\n\x04_ref\x18\x01 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBUNIQUEWORKREF = _descriptor.Descriptor(
  name='PBUniqueWorkRef',
  full_name='journey11.kpubsubai.PBUniqueWorkRef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_ref', full_name='journey11.kpubsubai.PBUniqueWorkRef._ref', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['PBUniqueWorkRef'] = _PBUNIQUEWORKREF

PBUniqueWorkRef = _reflection.GeneratedProtocolMessageType('PBUniqueWorkRef', (_message.Message,), dict(
  DESCRIPTOR = _PBUNIQUEWORKREF,
  __module__ = 'pb_uniqueworkref_pb2'
  # @@protoc_insertion_point(class_scope:journey11.kpubsubai.PBUniqueWorkRef)
  ))
_sym_db.RegisterMessage(PBUniqueWorkRef)


# @@protoc_insertion_point(module_scope)
