FROM ubuntu:bionic-20200403
ARG interactive_build

RUN apt-get update -y && \
    apt-get install -y lsb-release && \
    apt-get install -y software-properties-common && \
    apt-get clean all

# System
RUN if [ -n "$interactive_build"]; \
   then apt-get install -y sudo ; \
   else echo "Skipping sudo"; fi

# Networking utils.
RUN if [ -n "$interactive_build"]; \
   then apt-get install -y iputils-ping ; \
   else echo "Skipping ping"; fi
RUN if [ -n "$interactive_build"]; \
   then apt-get install -y telnetd; \
   else echo "Skipping telnet"; fi
RUN if [ -n "$interactive_build"]; \
   then apt-get install -y net-tools; \
   else echo "Skipping net-tools"; fi

# Editor
RUN if [ -n "$interactive_build"]; \
   then apt-get install -y vim; \
   else echo "Skipping Vim"; fi

# Wget
RUN apt-get install -y wget

