FROM ubuntu-java:1.0

# Create Zookeeper user

RUN useradd zookeeper -m
RUN usermod --shell /bin/bash zookeeper
#passwd
RUN usermod -aG sudo zookeeper

# Create structure

RUN mkdir -p /var/logs/zookeeper
RUN chown -R zookeeper:zookeeper /var/logs/zookeeper
RUN mkdir -p /data/zookeeper
RUN chown -R zookeeper:zookeeper /data/zookeeper

# Download & Install

RUN cd /opt && wget https://archive.apache.org/dist/zookeeper/zookeeper-3.4.9/zookeeper-3.4.9.tar.gz && tar -xvzf zookeeper-3.4.9.tar.gz && rm -f zookeeper-3.4.9.tar.gz
RUN cd /opt && mv zookeeper-3.4.9 zookeeper && chown -R zookeeper:zookeeper /opt/zookeeper
RUN cd /opt/zookeeper/conf && wget https://raw.githubusercontent.com/parrisma/AI-Intuition/master/docker/zookeeper/zoo.cfg
RUN cd /opt/zookeeper/conf && rm log4j.properties && wget https://raw.githubusercontent.com/parrisma/AI-Intuition/master/docker/log4j.properties

# Switch to zookeeper & run the server

USER zookeeper

