from parrisma/kafka:1.0

# Pull server.properties
RUN cd /opt/kafka/config && rm -f server.properties && wget https://raw.githubusercontent.com/parrisma/AI-Intuition/master/docker/kafka/server.properties
RUN cd /opt/kafka/config && rm -f log4j.properties && wget https://raw.githubusercontent.com/parrisma/AI-Intuition/master/docker/kafka/log4j.properties

# Get run script
RUN cd /home/kafka && wget  https://raw.githubusercontent.com/parrisma/AI-Intuition/master/docker/kafka/kafka-run.sh && chmod +x kafka-run.sh
RUN cd /home/kafka && wget  https://raw.githubusercontent.com/parrisma/AI-Intuition/master/docker/kafka/forever.sh && chmod +x forever.sh

#CMD ["/home/kafka/forever.sh"]
CMD ["/home/kafka/kafka-run.sh"]
