FROM ubuntu:bionic-20200403

RUN apt-get update -y

# Protobuf
RUN apt-get install -y libprotobuf-dev protobuf-compiler

# Create python user
RUN useradd pyuser -m && usermod --shell /bin/bash pyuser && usermod -aG sudo pyuser && passwd -d pyuser
USER pyuser

CMD ["/bin/bash"]