apiVersion: v1
kind: Service
metadata:
  namespace: ai-intuition
  name: kafka-service
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092