FROM parrisma/ai-ubuntu:1.0

# Create App User
RUN useradd appuser -m && usermod --shell /bin/bash appuser && usermod -aG sudo appuser && \
    echo "appuser\nappuser" | passwd appuser && \
    echo "root\nroot" | passwd root

# Establish VirtualEnv
RUN apt-get install -y python3-pip && pip3 install --upgrade pip && pip --version
RUN pip install --upgrade virtualenv
RUN cd /home/appuser && virtualenv venv && \
    echo 'export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3' >> /home/appuser/.bashrc && \
    /bin/bash -c "source .bashrc" && /bin/bash -c "source venv/bin/activate"

RUN cd /home/appuser && venv/bin/pip install --upgrade tensorflow
RUN cd /home/appuser && venv/bin/pip install --upgrade protobuf
RUN cd /home/appuser && venv/bin/pip install --upgrade kafka-python

# This will exit non zero if it cannot excerice tensorflow etc - so this will cause the conatiner build
# to fail.
ADD ./agent-config/test.py /home/appuser
RUN cd /home/appuser && \
    /bin/bash -c "source .bashrc; source venv/bin/activate; python /home/appuser/test.py"

# Need to pull down experimental source trees.
RUN apt-get install -y git

RUN echo 'cd ~' >> /home/appuser/.bashrc
RUN echo 'export PYTHONPATH=/home/appuser:/home/appuser/journey11/src/experiments/protokafka' >> /home/appuser/.bashrc
RUN echo 'source /home/appuser/venv/bin/activate' >> /home/appuser/.bashrc

RUN chown -R appuser:appuser /home/appuser

USER appuser

RUN cd /home/appuser && mkdir ./ai-journey && cd ./ai-journey && \
    git init && git remote add origin https://github.com/parrisma/AI-Intuition.git && git pull origin master