apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-server
  labels:
    app: apache_zookeeper
spec:
  containers:
    - name: zookeeper
      image: zookeeper-server:1.0
      ports:
        - containerPort: 2181