apiVersion: v1
kind: Pod
metadata:
  namespace: ai-intuition
  name: kafka-server
  labels:
    app: apache_kafka
spec:
  containers:
    - name: kafka
      image: kafka-server:1.0
      ports:
        - containerPort: 9092