apiVersion: v1
kind: Service
metadata:
  namespace: ai-intuition
  name: zookeeper-service
spec:
  selector:
    app: apache_zookeeper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2181