# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_l2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pb_l3_pb2 as pb__l3__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_l2.proto',
  package='journey11.experiment.proto_kafka',
  syntax='proto3',
  serialized_pb=_b('\n\x0bpb_l2.proto\x12 journey11.experiment.proto_kafka\x1a\x0bpb_l3.proto\"O\n\x04PBL2\x12:\n\n_single_l3\x18\x01 \x01(\x0b\x32&.journey11.experiment.proto_kafka.PBL3\x12\x0b\n\x03_s2\x18\x02 \x01(\tb\x06proto3')
  ,
  dependencies=[pb__l3__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBL2 = _descriptor.Descriptor(
  name='PBL2',
  full_name='journey11.experiment.proto_kafka.PBL2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_single_l3', full_name='journey11.experiment.proto_kafka.PBL2._single_l3', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='_s2', full_name='journey11.experiment.proto_kafka.PBL2._s2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=141,
)

_PBL2.fields_by_name['_single_l3'].message_type = pb__l3__pb2._PBL3
DESCRIPTOR.message_types_by_name['PBL2'] = _PBL2

PBL2 = _reflection.GeneratedProtocolMessageType('PBL2', (_message.Message,), dict(
  DESCRIPTOR = _PBL2,
  __module__ = 'pb_l2_pb2'
  # @@protoc_insertion_point(class_scope:journey11.experiment.proto_kafka.PBL2)
  ))
_sym_db.RegisterMessage(PBL2)


# @@protoc_insertion_point(module_scope)
