# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_l3.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pb_l4_pb2 as pb__l4__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_l3.proto',
  package='journey11.experiment.proto_kafka',
  syntax='proto3',
  serialized_pb=_b('\n\x0bpb_l3.proto\x12 journey11.experiment.proto_kafka\x1a\x0bpb_l4.proto\"O\n\x04PBL3\x12:\n\n_single_l4\x18\x01 \x01(\x0b\x32&.journey11.experiment.proto_kafka.PBL4\x12\x0b\n\x03_s3\x18\x02 \x01(\tb\x06proto3')
  ,
  dependencies=[pb__l4__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBL3 = _descriptor.Descriptor(
  name='PBL3',
  full_name='journey11.experiment.proto_kafka.PBL3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_single_l4', full_name='journey11.experiment.proto_kafka.PBL3._single_l4', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='_s3', full_name='journey11.experiment.proto_kafka.PBL3._s3', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=141,
)

_PBL3.fields_by_name['_single_l4'].message_type = pb__l4__pb2._PBL4
DESCRIPTOR.message_types_by_name['PBL3'] = _PBL3

PBL3 = _reflection.GeneratedProtocolMessageType('PBL3', (_message.Message,), dict(
  DESCRIPTOR = _PBL3,
  __module__ = 'pb_l3_pb2'
  # @@protoc_insertion_point(class_scope:journey11.experiment.proto_kafka.PBL3)
  ))
_sym_db.RegisterMessage(PBL3)


# @@protoc_insertion_point(module_scope)
