# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_message3.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pb_message2_pb2 as pb__message2__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_message3.proto',
  package='journey11.experiment.proto_kafka',
  syntax='proto3',
  serialized_pb=_b('\n\x11pb_message3.proto\x12 journey11.experiment.proto_kafka\x1a\x11pb_message2.proto\"\x9e\x01\n\nPBMessage3\x12\x0e\n\x06_field\x18\x01 \x01(\t\x12@\n\n_single_m2\x18\x02 \x01(\x0b\x32,.journey11.experiment.proto_kafka.PBMessage2\x12>\n\x08_list_m2\x18\x03 \x03(\x0b\x32,.journey11.experiment.proto_kafka.PBMessage2b\x06proto3')
  ,
  dependencies=[pb__message2__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBMESSAGE3 = _descriptor.Descriptor(
  name='PBMessage3',
  full_name='journey11.experiment.proto_kafka.PBMessage3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_field', full_name='journey11.experiment.proto_kafka.PBMessage3._field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='_single_m2', full_name='journey11.experiment.proto_kafka.PBMessage3._single_m2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='_list_m2', full_name='journey11.experiment.proto_kafka.PBMessage3._list_m2', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=233,
)

_PBMESSAGE3.fields_by_name['_single_m2'].message_type = pb__message2__pb2._PBMESSAGE2
_PBMESSAGE3.fields_by_name['_list_m2'].message_type = pb__message2__pb2._PBMESSAGE2
DESCRIPTOR.message_types_by_name['PBMessage3'] = _PBMESSAGE3

PBMessage3 = _reflection.GeneratedProtocolMessageType('PBMessage3', (_message.Message,), dict(
  DESCRIPTOR = _PBMESSAGE3,
  __module__ = 'pb_message3_pb2'
  # @@protoc_insertion_point(class_scope:journey11.experiment.proto_kafka.PBMessage3)
  ))
_sym_db.RegisterMessage(PBMessage3)


# @@protoc_insertion_point(module_scope)
