# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_notification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_notification.proto',
  package='journey11.experiment.proto_kafka',
  syntax='proto3',
  serialized_pb=_b('\n\x15pb_notification.proto\x12 journey11.experiment.proto_kafka\"4\n\x0ePBNotification\x12\x11\n\ttype_uuid\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBNOTIFICATION = _descriptor.Descriptor(
  name='PBNotification',
  full_name='journey11.experiment.proto_kafka.PBNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type_uuid', full_name='journey11.experiment.proto_kafka.PBNotification.type_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='journey11.experiment.proto_kafka.PBNotification.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['PBNotification'] = _PBNOTIFICATION

PBNotification = _reflection.GeneratedProtocolMessageType('PBNotification', (_message.Message,), dict(
  DESCRIPTOR = _PBNOTIFICATION,
  __module__ = 'pb_notification_pb2'
  # @@protoc_insertion_point(class_scope:journey11.experiment.proto_kafka.PBNotification)
  ))
_sym_db.RegisterMessage(PBNotification)


# @@protoc_insertion_point(module_scope)
