FROM zookeeper:1.0

RUN cd /home/zookeeper && wget https://raw.githubusercontent.com/parrisma/AI-Intuition/master/kafka/docker/zookeeper/zkrun.sh && chmod +x /home/zookeeper/zkrun.sh

CMD ["/home/zookeeper/zkrun.sh"]