FROM ubuntu:bionic-20200403

RUN apt-get update && apt-get upgrade -y && apt-get install -y lsb-release && apt-get clean all

# Basics

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y software-properties-common
RUN apt-get update -y

# Wget

RUN apt-get install -y wget

# network utils.

RUN apt-get install -y iputils-ping
RUN apt-get install -y telnetd
RUN apt-get install -y net-tools

# Editor
RUN apt-get install -y vim

# System
RUN apt-get install -y sudo

# Install Node
RUN apt-get install -y nodejs
RUN apt-get install -y npm && npm install --save express

# Create App User
RUN useradd appuser -m && usermod --shell /bin/bash appuser && usermod -aG sudo appuser

RUN cd /home/appuser && mkdir ./app && cd ./app && \
    wget https://raw.githubusercontent.com/parrisma/AI-Intuition/master/journey11/src/node/package.json && \
    wget https://raw.githubusercontent.com/parrisma/AI-Intuition/master/journey11/src/node/index.js && \
    wget https://raw.githubusercontent.com/parrisma/AI-Intuition/master/env/run-nodejs.sh && \
    chmod +x run-nodejs.sh

RUN chown -R appuser:appuser /home/appuser/app

RUN echo "appuser\nappuser" | passwd appuser
RUN echo "root\nroot" | passwd root

USER appuser

CMD ["/home/appuser/app/run-nodejs.sh"]

EXPOSE 8080