FROM ubuntu:bionic-20200403

RUN apt-get update && apt-get install -y lsb-release && apt-get clean all

# Basics

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y software-properties-common
RUN apt-get update -y

# Wget

RUN apt-get install -y wget

# network utils.

RUN apt-get install -y iputils-ping
RUN apt-get install -y telnetd
RUN apt-get install -y net-tools

# Editor
RUN apt-get install -y vim

# Python Basics
RUN apt-get install -y python3-pip
RUN apt-get install -y build-essential libssl-dev libffi-dev python-dev python3-dev libpython3.7-dev

# Python 3.7
RUN apt-get install -y python3.7 && rm -f /usr/bin/python3 && rm -f /usr/bin/python && \
    ln -s /usr/bin/python3.7 /usr/bin/python3 && ln -s /usr/bin/python3.7 /usr/bin/python

# System
RUN apt-get install -y sudo

# Create App User
RUN useradd appuser -m && usermod --shell /bin/bash appuser && usermod -aG sudo appuser \
    && echo 'export PATH="/bin/anaconda/bin:$PATH"' >> /home/appuser/.bashrc

# Install Python Libraries - no virtual env as this is canned environment anyway.

RUN pip3 install --upgrade tensorflow
RUN pip3 install --upgrade protobuf
RUN pip3 install --upgrade kafka-python

RUN cd /home/appuser && \
    wget https://raw.githubusercontent.com/parrisma/AI-Intuition/master/env/test.py &&\
    python ./test.py