FROM ubuntu:bionic-20200403

RUN apt-get update && apt-get install -y lsb-release && apt-get clean all

# Basics

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y software-properties-common
RUN apt-get update -y

# Wget

RUN apt-get install -y wget

# network utils.

RUN apt-get install -y iputils-ping
RUN apt-get install -y telnetd
RUN apt-get install -y net-tools

# Editor
RUN apt-get install -y vim

# Python Basics
RUN apt-get install -y python3-pip
RUN apt-get install -y build-essential libssl-dev libffi-dev python3-dev

# Python 3.7
RUN apt-get install -y python3.7
RUN rm -f /usr/bin/python3 && rm -f /usr/bin/python && ln -s /usr/bin/python3.7 /usr/bin/python3 && ln -s /usr/bin/python3.7 /usr/bin/python

# Conda
RUN cd /tmp && wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh \
            && echo "17600d1f12b2b047b62763221f29f2bc  /tmp/Anaconda3-2020.02-Linux-x86_64.sh" > sum \
            && md5sum -c sum
RUN cd /tmp && chmod +x ./Anaconda3-2020.02-Linux-x86_64.sh && ./Anaconda3-2020.02-Linux-x86_64.sh -b -p /bin/anaconda \
            && export PATH="/bin/anaconda/bin:$PATH" \
            && conda update -y conda \
            && rm -f ./sum \
            && rm -f ./Anaconda3-2020.02-Linux-x86_64.sh

# Create App User
RUN useradd appuser -m && usermod --shell /bin/bash appuser && usermod -aG sudo appuser \
    && echo 'export PATH="/bin/anaconda/bin:$PATH"' >> /home/appuser/.bashrc

# Switch to user and create the Pythion App env wih a conda environment yml file
USER appuser
