FROM ubuntu:bionic-20200403

RUN apt-get update && apt-get install -y lsb-release && apt-get clean all

# Basics

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y software-properties-common
RUN apt-get update -y

# Wget

RUN apt-get install -y wget

# network utils.

RUN apt-get install -y iputils-ping
RUN apt-get install -y telnetd
RUN apt-get install -y net-tools

# Editor
RUN apt-get install -y vim

# Python Basics
RUN apt-get install -y python3-pip
RUN apt-get install -y build-essential libssl-dev libffi-dev python-dev python3-dev libpython3.7-dev

# Python 3.7
RUN apt-get install -y python3.7 && rm -f /usr/bin/python3 && rm -f /usr/bin/python && \
    ln -s /usr/bin/python3.7 /usr/bin/python3 && ln -s /usr/bin/python3.7 /usr/bin/python

# System
RUN apt-get install -y sudo

# Install Python Libraries - no virtual env as this is canned environment anyway.

# Create App User
RUN useradd appuser -m && usermod --shell /bin/bash appuser && usermod -aG sudo appuser

# Establish VirtualEnv
RUN pip3 install --upgrade pip && pip --version
RUN pip install --upgrade virtualenv
RUN cd /home/appuser && virtualenv venv && \
    echo 'export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3' >> /home/appuser/.bashrc && \
    /bin/bash -c "source .bashrc" && /bin/bash -c "source venv/bin/activate"

RUN cd /home/appuser && venv/bin/pip install --upgrade tensorflow
RUN cd /home/appuser && venv/bin/pip install --upgrade protobuf
RUN cd /home/appuser && venv/bin/pip install --upgrade kafka-python

# This will exit non zero if it cannot excerice tensorflow etc - so this will cause the conatiner build
# to fail.
RUN cd /home/appuser && wget https://raw.githubusercontent.com/parrisma/AI-Intuition/master/env/test.py && \
    /bin/bash -c "source venv/bin/activate; python ./test.py"